### ISSUE TITLE
Research: Include API documentation in other languages

### ISSUE THREAD

**Issue by Chriscbr** [cdk8s-team/cdk8s#641] opened 2021-08-11 18:40 UTC
A simple solution for this is to link users directly to the Construct Hub, since it can display the API reference in all of the languages. As of posting the Construct Hub only currently supports TypeScript and Python docs, so we might want to link to go docs on the cdk8s website in the meantime, such as:

- https://pkg.go.dev/github.com/cdk8s-team/cdk8s-core-go/cdk8s
- https://pkg.go.dev/github.com/cdk8s-team/cdk8s-plus-17-go/cdk8splus17

**Comment by iliapolo** [comment] 2021-08-17 08:56
We should also think about Java API Reference - what would it take to get at least the standard JavaDocs out there?

**Comment by eladb** [comment] 2021-08-17 09:00
> We should also think about Java API Reference - what would it take to get at least the standard JavaDocs out there?

Why not double down on jsii-docgen and implement java support there?

**Comment by iliapolo** [comment] 2021-08-18 11:12
We decided to try and embed the latest API reference produced by `jsii-docgen` into the `cdk8s.io` website to provide both a better API Reference as well as reduce context switching caused by linking to `constructs.dev`. 

Our current action plan for this is:

1. Embed TypeScript and Python API Reference in `cdk8s.io`
2. Implement Java support for `jsii-docgen`
3. Embed Java in `cdk8s.io`
4. Provide links to the golang auto-generated API Reference as a solution for golang until `jsii-docgen` support it.

Closing this Research ticket and i'll follow up with concrete implementation tickets.

**Closed by iliapolo** 2021-08-18 11:12 UTC
Labels: feature-request, effort/small, priority/p1
